cat config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
development:
  adapter: postgresql
  database: db/database_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: db/database_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: db/database_production
  pool: 5
  timeout: 5000